### ISSUE TITLE
where can i get the data used in this experiments?

### ISSUE THREAD

**Issue by Blue1993** [addb-swstarlab/Redis-RS-OtterTune#1]
It seems to be a very interesting github.
Nowadays, I am into Redis parameters optimization.
However, it seems that only the code is currently public on github and the data is not.
Are you willing to out of disclosing the data you used for the experiment?

**Comment by kimkyeonghun** [comment]
we don't intend to disclose the data used in the experiment.
You can produce data using redis-sample-generation.
